name: Generate and deploy docs to gh-pages

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.ref }}

            - name: Install dependencies
              run: |
                  npm install
                  npm install --global jsdoc typedoc typedoc-plugin-markdown

            - name: Generate documentation
              run: |
                  npm run docs:js && npm run docs:ts && npm run docs:md

            - name: Configure Git
              run: |
                  git config --global user.email ${{ secrets.EMAIL }}
                  git config --global user.name ${{ secrets.USERNAME }}

            - name: Publish to gh-pages
              run: npm run docs:publish

            - name: Check for errors
              if: ${{ job.status != 'success' }}
              run: |
                  echo "Documentation generation or deployment failed! Please check the logs for more information."
